version: '3.8'
services:
  app:
    image: ${DOCKERHUB_USERNAME}/peopleofdelivery:latest
    environment:
      SPRING_DATASOURCE_URL: ${LOCAL_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${LOCAL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${LOCAL_DB_PASSWORD}
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: ${DOCKERHUB_USERNAME}:latest
    environment:
      POSTGRES_DB: ${LOCAL_DB_URL}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
