version: '3.8'
services:
  app:
    image: ${DOCKERHUB_USERNAME}/peopleofdelivery:latest
    volumes:
      - ./application.yml:/app/config/application.yml:ro
      - ./.env:/app/.env:ro
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
